- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Installing Multiple Packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - mysql
        - php
        - unzip